#!/bin/sh

### BEGIN INIT INFO
# Provides:          mytest
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable OpenVPN client service to conect the donation box with the Donation-box VPN.
### END INIT INFO

set -e 
#public_ip=$(curl -s https://ipinfo.io/ip)

case "$1" in
  start)
	public_ip=$(curl -s https://ipinfo.io/ip)
#    log_success_msg "______________KALIMERA__________________ 1 "
#    log_failure_msg "______________KALIMERA__________________ 2 "
#    log_warning_msg "______________KALIMERA__________________ 3 "
    echo "_______________foo______________ [1]" > /dev/console
	echo -n "[  \033[32mOK\033[0m  ] " > /dev/console
	echo "The OpenVPN client started succesfully." > /dev/console

	echo "Your public ip is : ---------- " > /dev/console
    echo "_______________foo______________ [1.1]" > /dev/console
    sleep 200
    ;;
  stop)
    echo "-----------> Stopping Service !!!!!!!!!!!!!!!!!!!!!!!!" > /dev/console
    echo "_______________foo______________ [2]___________" > /dev/console
    sleep 20
    ;;
  *)
    echo "Usage: /etc/init.d/test {start|stop}"
    sleep 20
    exit 1
    ;;
esac

# Green succesfull message.
#echo -e "\e[1m\e[32m$public_ip\e[0m"

exit 0




