#!/bin/sh

### BEGIN INIT INFO
# Provides:          donationbox
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Should-Start:      openvpn
# Should-Stop:       openvpn
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Donation-box startup service.
# Description:       This script will check in a first stage the availability of
#                    networking and informs the user.
### END INIT INFO


set -e


check_connection()
{
        printf "\n"

        interfaces=$(ls /sys/class/net)
        internet_activated=false
        vpn_activated=false

        for inter in $interfaces
        do
                inet=$(ifconfig "$inter" | grep -c "inet" )
                if [ $inter != 'lo' ] && [ $inet ]
                then
                        ip=$(ip addr show "$inter" | awk '/inet /{print $2}' | cut -d/ -f1)  # By Diomidis Spinellis

                        if [ $ip ]
                        then
                                printf " * IP address for %s:%+15s\n" "$inter" "$ip" > /dev/console
                                internet_activated=true
                        fi

                        if [ $inter = 'tun0' ]
                        then
                                vpn_activated=true
                        fi

                fi
        done

        if [ $internet_activated = true ]
        then
                public_ip=$(curl -s https://ipinfo.io/ip)

                echo -n "\n * Public IP " > /dev/console
                echo "[ \033[1m\033[32m$public_ip\033[0m ]" > /dev/console

                if [ $vpn_activated = true ]
                then
                        echo -n "\n[  \033[32mOK\033[0m  ] " > /dev/console
                        echo "The OpenVPN client started succesfully." > /dev/console
                else
                        echo '\n[\033[31mFAILED\033[0m] \033[31mFailed to start OpenVPN connection.\033[0m' > /dev/console
                        echo '\033[31m ** \033[0m \033[91mFailed to start OpenVPN connection.\033[0m \033[31m ** \033[0m' > /dev/console
                fi
	else
		echo "*\033[31m * \033[0m* \033[31mNo internet connection.\033[0m *\033[31m * \033[0m*" > /dev/console

        fi


}




case "$1" in
  start)

    check_connection

    ;;
  stop)
    ;;
  *)
    echo "Usage: /etc/init.d/test {start|stop}"
    exit 1
    ;;
esac


exit 0
